/*
* Generated by dtrace(1M).
*/

#ifndef	_PROBES_H
#define	_PROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#include <sys/sdt.h>

#if _DTRACE_VERSION

#define	CONTEXT_EVENT_ARGS(arg0, arg1, arg2, arg3) \
__dtrace_context___event_args(arg0, arg1, arg2, arg3)
#ifndef	__sparc
#define	CONTEXT_EVENT_ARGS_ENABLED() \
__dtraceenabled_context___event_args()
#else
#define	CONTEXT_EVENT_ARGS_ENABLED() \
__dtraceenabled_context___event_args(0)
#endif
#define	CONTEXT_EVENT_SIMPLE() \
__dtrace_context___event_simple()
#ifndef	__sparc
#define	CONTEXT_EVENT_SIMPLE_ENABLED() \
__dtraceenabled_context___event_simple()
#else
#define	CONTEXT_EVENT_SIMPLE_ENABLED() \
__dtraceenabled_context___event_simple(0)
#endif


extern void __dtrace_context___event_args(uint8_t, uint32_t, uint64_t, unsigned char *);
#ifndef	__sparc
extern int __dtraceenabled_context___event_args(void);
#else
extern int __dtraceenabled_context___event_args(long);
#endif
extern void __dtrace_context___event_simple(void);
#ifndef	__sparc
extern int __dtraceenabled_context___event_simple(void);
#else
extern int __dtraceenabled_context___event_simple(long);
#endif

#else

#define	CONTEXT_EVENT_ARGS(arg0, arg1, arg2, arg3)
#define	CONTEXT_EVENT_ARGS_ENABLED() (0)
#define	CONTEXT_EVENT_SIMPLE()
#define	CONTEXT_EVENT_SIMPLE_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */