/*
* Generated by dtrace(1M).
*/
#ifndef	_PROBES_H
#define	_PROBES_H
#include <unistd.h>
#ifdef	__cplusplus
extern "C" {
#endif
#include <sys/sdt.h>
#if _DTRACE_VERSION
#define	NET_INBOUND_MESSAGE(arg0, arg1, arg2, arg3) \
__dtrace_net___inbound_message(arg0, arg1, arg2, arg3)
#ifndef	__sparc
#define	NET_INBOUND_MESSAGE_ENABLED() \
__dtraceenabled_net___inbound_message()
#else
#define	NET_INBOUND_MESSAGE_ENABLED() \
__dtraceenabled_net___inbound_message(0)
#endif
extern void __dtrace_net___inbound_message(uint8_t, uint32_t, uint64_t, unsigned char *);
#ifndef	__sparc
extern int __dtraceenabled_net___inbound_message(void);
#else
extern int __dtraceenabled_net___inbound_message(long);
#endif
#else
#define	NET_INBOUND_MESSAGE(arg0, arg1, arg2, arg3)
#define	NET_INBOUND_MESSAGE_ENABLED() (0)
#endif
#ifdef	__cplusplus
}
#endif
#endif	/* _PROBES_H */