/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* NET_INBOUND_MESSAGE ( uint8_t, uint32_t, uint64_t, unsigned char * ) */
#if defined STAP_SDT_V1
#define NET_INBOUND_MESSAGE_ENABLED() __builtin_expect (inbound_message_semaphore, 0)
#define net_inbound_message_semaphore inbound_message_semaphore
#else
#define NET_INBOUND_MESSAGE_ENABLED() __builtin_expect (net_inbound_message_semaphore, 0)
#endif
__extension__ extern unsigned short net_inbound_message_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define NET_INBOUND_MESSAGE(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (net, inbound_message, arg1, arg2, arg3, arg4)

