/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROBES_H
#define	_PROBES_H

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED
#include <unistd.h>

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */

#ifdef	__cplusplus
extern "C" {
#endif

#define NET_STABILITY "___dtrace_stability$net$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define NET_TYPEDEFS "___dtrace_typedefs$net$v2"

#if !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED

#define	NET_INBOUND_MESSAGE(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " NET_TYPEDEFS); \
	__dtrace_probe$net$inbound_message$v1$75696e74385f74$75696e7433325f74$75696e7436345f74$756e7369676e65642063686172202a(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " NET_STABILITY); \
} while (0)
#define	NET_INBOUND_MESSAGE_ENABLED() \
	({ int _r = __dtrace_isenabled$net$inbound_message$v1(); \
		__asm__ volatile(""); \
		_r; })


extern void __dtrace_probe$net$inbound_message$v1$75696e74385f74$75696e7433325f74$75696e7436345f74$756e7369676e65642063686172202a(uint8_t, uint32_t, uint64_t, const unsigned char *);
extern int __dtrace_isenabled$net$inbound_message$v1(void);

#else

#define	NET_INBOUND_MESSAGE(arg0, arg1, arg2, arg3) \
do { \
	} while (0)
#define	NET_INBOUND_MESSAGE_ENABLED() (0)

#endif /* !defined(DTRACE_PROBES_DISABLED) || !DTRACE_PROBES_DISABLED */


#ifdef	__cplusplus
}
#endif

#endif	/* _PROBES_H */
